name: notesapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_screenutil: ^5.9.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  meta: ^1.15.0
  modal_progress_hud_nsn: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

fonts:
  - family: Mochiy Pop One
    fonts:
      - asset: assets/fonts/MochiyPopOne-Regular.ttf
